version: '3.9'

services:
  db:
    image: postgis/postgis:13-3.1
    container_name: postgis
    environment:
      POSTGRES_DB: arapuca
      POSTGRES_USER: arapuca
      POSTGRES_PASSWORD: arapuca
    volumes:
      - postgis_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  django:
    build: .
    command: sh -c "python src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./django:/usr/project/app
    ports:
      - "8000:8000"
    depends_on:
      - db

#  geoserver:
#    image: osgeo/geoserver:latest
#    environment:
#      GEOSERVER_ADMIN_PASSWORD: geoserver
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db

volumes:
  postgis_data:
