# Generated by Django 4.2.14 on 2024-07-18 02:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rural_property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('scientific_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='nome científico')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'inseto',
                'db_table': 'insect',
            },
        ),
        migrations.CreateModel(
            name='InsectTrapType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('insect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insect_trap.insect', verbose_name='inseto')),
            ],
            options={
                'verbose_name': 'tipo de armadilha',
                'verbose_name_plural': 'tipos de armadilhas',
                'db_table': 'insect_trap_type',
            },
        ),
        migrations.CreateModel(
            name='InsectTrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rural_property.field', verbose_name='talhão')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insect_trap.insecttraptype', verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'armadilha',
                'db_table': 'insect_trap',
            },
        ),
    ]
