# Generated by Django 4.2.14 on 2024-07-18 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insect_trap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insecttrap',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
            preserve_default=False,
        ),
    ]
