# Generated by Django 4.2.14 on 2024-08-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insect_trap', '0003_insecttrapresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='insecttraptype',
            name='infestation_alert_level',
            field=models.PositiveIntegerField(help_text='em número de insetos', null=True, verbose_name=' nível alerta de infestação'),
        ),
    ]
