# Generated by Django 4.2.14 on 2024-08-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insect_trap', '0004_insecttraptype_infestation_alert_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insecttraptype',
            name='infestation_alert_level',
            field=models.PositiveIntegerField(help_text='em número de insetos', verbose_name=' nível alerta de infestação'),
        ),
    ]
